### ISSUE TITLE
Add more sites

### ISSUE THREAD

**Issue by Semro** [arosh/ublacklist-stackoverflow-translation#1]
You can add a lot of machine translated SO sites from here https://github.com/Taraflex/Back2stackoverflow

**Comment by arosh** [comment]
@Semro 
Thank you for reporting great related work.

Some sites on the list seem to "provide" translated SO for Japanese. Therefore, I decided to add the following items to the blacklist. Thanks.

```
*://code.i-harness.com/*
*://stackoverrun.com/*
*://code-adviser.com/*
```
