### ISSUE TITLE
Not translation but copy

### ISSUE THREAD

**Issue by flat35hd99** [arosh/ublacklist-stackoverflow-translation#108]
evidence
- [original on stackoverflow](https://stackoverflow.com/questions/41025416/read-data-dat-file-with-pandas)
- [copy site](https://coderedirect.com/questions/178019/read-data-dat-file-with-pandas)

**Comment by arosh** [comment]
This domain is blocked by the following entry. Is there something troubling you?

https://github.com/arosh/ublacklist-stackoverflow-translation/blob/0e3fdd512f5278e9e6a990b3b68660ad7ee7e886/domain-list.yml#L390-L392

**Comment by flat35hd99** [comment]
I'm so sorry. I forgot to input this repository on my new computer's chrome.
and It works well. The site is just blocked.
