### ISSUE TITLE
`christfever.in`

### ISSUE THREAD

**Issue by yedpodtrzitko** [arosh/ublacklist-stackoverflow-translation#110]
Hello,
`christfever.in` seems to be yet another datadump of Stackoverflow. Example:

Google query:
https://www.google.com/search?q=%22Im+not+sure+why+the+program+return+true+when+the+string+contains+chinese+characters%22

SO question:
https://stackoverflow.com/questions/65011034/how-does-isalnum-and-isalpha-works-in-python-returning-true-when-chinese-is-i

question copy:
https://christfever.in/index.php?threads/how-does-isalnum-and-isalpha-works-in-python-returning-true-when-chinese-is-included.636732/

Cheers

**Comment by arosh** [comment]
Thanks. Resolved by #111.
