### ISSUE TITLE
www.it-swarm-fr.com

### ISSUE THREAD

**Issue by quenhus** [arosh/ublacklist-stackoverflow-translation#112]
French translation of StackOverflow.
`*://www.it-swarm-fr.com/*`

Original: https://stackoverflow.com/questions/50435455/how-to-install-gmp-extension-for-php-7-2-using-mamp-on-osx
Evidence: https://www.it-swarm-fr.com/fr/php/comment-installer-lextension-gmp-pour-php-7.2-en-utilisant-mamp-sur-osx/838751599/

**Comment by arosh** [comment]
Thanks. Resolved by #113.
