### ISSUE TITLE
機械翻訳をせずに複製しているサイトはリストに追加可能ですか？

### ISSUE THREAD

**Issue by CRC32EX** [arosh/ublacklist-stackoverflow-translation#135]
機械翻訳をせずに原文そのまま複製しているWebサイトが存在していました。
本リポジトリは翻訳をしたサイトを除外という趣旨だったのでIssueを開きました。

個人的には邪魔なので除外してもいいと思っておりますが本リポジトリとしての判断をお願いしたいです。

- 複製サイト<br>https://stackguides.com/questions/55582335
- オリジナルサイト<br>https://stackoverflow.com/questions/55582335

**Comment by arosh** [comment]
@CRC32EX 
> 機械翻訳をせずに複製しているサイトはリストに追加可能ですか？

そのようなサイトがあまりにも増えすぎてしまったため、最近は受け入れています。
恒等変換も機械翻訳の一種であるという解釈をしました。

> ただし「機械翻訳」には恒等変換を含みます。つまり Stack Exchange が運営するサイト群の内容をそのままコピーしたページを機械的に生成しているドメインも対象となる場合があります。

https://github.com/arosh/ublacklist-stackoverflow-translation/blob/2f330611f949ccf6dcd643866198189298c41ea0/CONTRIBUTING.md#%E5%8F%97%E3%81%91%E5%85%A5%E3%82%8C%E5%9F%BA%E6%BA%96
