### ISSUE TITLE
bugfix.plus

### ISSUE THREAD

**Issue by CRC32EX** [arosh/ublacklist-stackoverflow-translation#15]
# ドメイン
```
bugfix.plus
```

# 例
- 機械翻訳ページ
https://bugfix.plus/info-83047.htm

- 元ページ
https://stackoverflow.com/questions/61864520/qemu-installating-ubuntu-through-iso-gets-stuck-shows-svm-cpu-bit-warning

**Comment by arosh** [comment]
Resolved by #13
