### ISSUE TITLE
www.aimz8.com

### ISSUE THREAD

**Issue by CRC32EX** [arosh/ublacklist-stackoverflow-translation#19]
# ドメイン
```
www.aimz8.com
```

# 例1
- https://www.aimz8.com/jp/?p=76438
- https://stackoverflow.com/questions/64602507/how-to-find-the-closest-match-sets-of-data

# 例2
- https://www.aimz8.com/jp/?p=76487
- https://ja.stackoverflow.com/questions/71629/if%E6%96%87%E3%82%92%E5%90%AB%E3%82%80python%E3%81%AE%E8%A1%A8%E8%A8%98%E3%82%921%E8%A1%8C%E3%81%AB%E3%81%BE%E3%81%A8%E3%82%81%E3%81%9F%E3%81%84

**Comment by CRC32EX** [comment]
機械翻訳すらされていない単なる転載サイトですがリストに掲載可能ですか？

**Comment by arosh** [comment]
@CRC32EX 
コントリビューションが増えてきたので、そろそろ掲載基準を明確にしようと思います。
少し時間を下さい。
このドメイン自体はブロックする方向で進めようと思います。

**Comment by arosh** [comment]
ページによって機械翻訳されているかどうかが異なるようでした。機械翻訳によって生成されたページも見つけたので承認します。

* https://www.aimz8.com/jp/?p=32659
* https://stackoverflow.com/questions/16199734/creating-dynamic-linq-expression-tree-against-nested-odata
