### ISSUE TITLE
接続不可能なドメインはリストから削除するべき？

### ISSUE THREAD

**Issue by arosh** [arosh/ublacklist-stackoverflow-translation#23]
以下のドメインは現在接続できないか、ドメインが失効しているようです。これらのドメインはリストから削除するべきでしょうか？

* `codeday.me`
* `www.code-adviser.com`
* `src-bin.com`
* `*.programqa.com`

**Comment by CRC32EX** [comment]
削除して問題ないと思います。
一応案だけ思いつく限りだとこんな感じでしょうか。
aroshさんに最終的な判断はおまかせします！

1. 失効してるドメインを見つけ次第リストから削除する
2. 一定期間様子を見て継続する意思がなさそうであれば削除する
3. 失効ドメインを見つけ次第削除し、GitHub Actions等を利用して一定時間ごとににアクセスする。復活した場合リストに加える
