### ISSUE TITLE
追加依頼

### ISSUE THREAD

**Issue by CRC32EX** [arosh/ublacklist-stackoverflow-translation#4]
# 追加依頼
```
366service.com
```

# 例
- 機械翻訳ページ  
http://www.366service.com/jp/qa/a550dc2388b592d50f83bf3b3369f0c5

- 元ページ
https://stackoverflow.com/questions/58109626/how-to-match-key-iv-generated-by-c-sharp-and-js-cryptojs

**Comment by arosh** [comment]
@CRC32EX 
確認しました。報告ありがとうございます。
da7d010693e71c51b4b037f79902e2f481bd6628 で追加しました。
