### ISSUE TITLE
[ojit.com]追加依頼

### ISSUE THREAD

**Issue by CRC32EX** [arosh/ublacklist-stackoverflow-translation#5]
# 追加依頼
```
ojit.com
```
`ojit.com`は`coder.work` にリダイレクトする仕様のようです。

# 例
- 機械翻訳ページ
https://ja.ojit.com/so/linux/137072  
![image](https://user-images.githubusercontent.com/25629617/80800455-79c55000-8be4-11ea-987e-361a37a764ea.png)

- 元ページ
https://stackoverflow.com/questions/3129608/is-there-any-modern-review-of-solutions-to-the-10000-client-sec-problem

**Comment by arosh** [comment]
@CRC32EX 
Thank you for the report and feedback.
Resolved by d29b072.
