### ISSUE TITLE
bleepcoder.com

### ISSUE THREAD

**Issue by kounoike** [arosh/ublacklist-stackoverflow-translation#50]
https://bleepcoder.com/ja/metabase/419604485/time-is-showing-24-00-instead-of-00-00
https://github.com/metabase/metabase/issues/9538

**Comment by arosh** [comment]
@kounoike 
This is not a translated site of Stack Exchange. Thank you for your attention to this project.

**Comment by CRC32EX** [comment]
Bleepcoder.com is GitHub issues translation website.
The original post is https://github.com/metabase/metabase/issues/9538

If the amount of GitHub translation website increases, please make consider create new repository for GitHub blacklist.
I can contribute, when i found like this website.

**Comment by CRC32EX** [comment]
Bleepcoder.com is GitHub issues translation website.
The original post is `https://github.com/metabase/metabase/issues/9538`

If the amount of GitHub translation website increases, please make consider create new repository for GitHub blacklist.
I can contribute, when i found like this website.

**Comment by arosh** [comment]
@kounoike @CRC32EX 
Thank you for your comment. I posted #51 to gather information about translated-GitHub. If you find translated-GitHub sites, please comment on it. If the number of such sites reaches 4+, I will launch a new project named ublacklist-github-translation.
