### ISSUE TITLE
ublacklist-github-translation

### ISSUE THREAD

**Issue by arosh** [arosh/ublacklist-stackoverflow-translation#51]
If you find translated-GitHub sites, please comment on this issue. If the number of such sites reaches 4+, I will launch a new project named ublacklist-github-translation.

**Comment by arosh** [comment]
`*://bleepcoder.com/*` reported by kounoike in #50.

**Comment by arosh** [comment]
`githubja.com` delivers machine-translated READMEs of popular repositories.

**Comment by HeavyOranJS** [comment]
`*://gitmemory.com` is not a translation site, but rather a plain ripoff of `github.com`. I propose to include such sites in blacklist too.
  evidence: https://www.gitmemory.com/issue/dbeaver/dbeaver/232/528912919
  original: https://github.com/dbeaver/dbeaver/issues/232

**Comment by udaken** [comment]
Hi.I found it too.

https://ask.csdn.net/questions/6197578
original: sakura-editor/sakura#251

**Comment by arosh** [comment]
`https://giters.com/arosh/ublacklist-stackoverflow-translation/issues/51` serves a clone of this page.

**Comment by arosh** [comment]
Add `githubmemory.com`

evidence: `https://githubmemory.com/repo/TrustedWebPromotionCouncil/Documents/issues`
original: `https://github.com/TrustedWebPromotionCouncil/Documents/issues`

**Comment by arosh** [comment]
[ublacklist-github-translation](https://github.com/arosh/ublacklist-github-translation) has been launched!!
