### ISSUE TITLE
stackoverflow以外の質問サイトを用いた機械翻訳サイトについて

### ISSUE THREAD

**Issue by matsu4ki** [arosh/ublacklist-stackoverflow-translation#57]
## 概要

`teratail.com`に記載されているサイトを発見しました。
ブロックリストへの追加は可能でしょうか？

本リポジトリはstackoverflowに対しての機械翻訳サイトをブロックためにあると思いますが、
質問サイトの機械翻訳ページをブロックするといった、本質からはズレていないと判断しissueとして投げました。

## evidence

- tutorialfor.com
  - https://teratail.com/questions/190159
  - https://www.tutorialfor.com/questions-133117.htm

**Comment by arosh** [comment]
@matsu4ki 
ご報告ありがとうございます。
おそらくこのフィルタの利用者のほとんどの方はこのドメインをブロックの対象に追加することに同意してくてくれるのではないかとは思いつつも、Stack Exchange 以外のサイトを翻訳したサイトの追加は慎重に判断したいと考えています。
判断に悩むサイトの追加の提案が増えてきた場合にプロジェクトの運営が難しくなってしまうためです。
同じように teratail を機械翻訳したサイトが増えてきた場合には別のリポジトリでプロジェクトを運用したいと思います (#58)。

**Comment by teohhanhui** [comment]
Just have multiple lists in the same repository? It'll be easy to compile a master list which combines everything too.
