### ISSUE TITLE
steakrecords.com

### ISSUE THREAD

**Issue by CRC32EX** [arosh/ublacklist-stackoverflow-translation#6]
# ドメイン
```
steakrecords.com
```

# 例
- 機械翻訳ページ
https://steakrecords.com/ja/856480-easyui-and-foundation-conflict-zurb-foundation-jquery-easyui.html

- 元ページ
https://stackoverflow.com/questions/31248509/easyui-and-foundation-conflict

**Comment by arosh** [comment]
Resolved by #7
