### ISSUE TITLE
`www.it-swarm-ja.com`

### ISSUE THREAD

**Issue by kangetsu121** [arosh/ublacklist-stackoverflow-translation#61]
I found another `www.it-swarm-(ja|jp). *` domain which is not registered in `domain-list.yml` and `uBlacklist.txt` yet.
Please consider adding this to the blacklist, thank you.

- domain: `www.it-swarm-ja.com`
- example
  - original: https://stackoverflow.com/questions/46955147/enter-with-keyup-event-not-working-in-vue
  - evidence: https://www.it-swarm-ja.com/ja/javascript/vue%E3%81%A7%E5%8B%95%E4%BD%9C%E3%81%97%E3%81%AA%E3%81%84keyup%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%81%A7%E5%85%A5%E5%8A%9B%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84/835790755/

**Comment by arosh** [comment]
@kangetsu121 
Thank you for your report.
Resolved by 9202077f64903e53a89f498ec0bb42a762e11275.
