### ISSUE TITLE
ja.culinarydegree.info & ja.safehavenpetrescue.org

### ISSUE THREAD

**Issue by Tan90909090** [arosh/ublacklist-stackoverflow-translation#72]
# ja.culinarydegree.info
- original: https://stackoverflow.com/questions/13054371/programmatically-switch-audio-devices-on-windows-7/20270535
- evidence: https://ja.culinarydegree.info/835697-programmatically-switch-audio-devices-on-SGPPFR
 
# ja.safehavenpetrescue.org
- original: https://stackoverflow.com/questions/63978924/how-to-keep-network-services-alive-for-an-app-in-chroot-on-android-device-when-t
- evidence: https://ja.safehavenpetrescue.org/328316-how-to-keep-network-services-IVTLBP

**Comment by arosh** [comment]
Resolved by #73. Thanks.
