### ISSUE TITLE
GitHubのIssueを機械翻訳したサイトについて

### ISSUE THREAD

**Issue by 108EAA0A** [arosh/ublacklist-stackoverflow-translation#74]
# 概要

#57 と似ていますが、GitHubは質問サイトとは言えないので別のissueにさせて頂きました

かなり微妙なラインではあるかとは思いましたが、機械翻訳サイトを検索結果から除外したいという趣旨からはズレてないと判断したので一応報告させて頂きました

恐らくこのサイトもこのリポジトリにはそぐわないと思うのですが、 https://github.com/arosh/ublacklist-stackoverflow-translation/issues/57#issuecomment-822382813 にある

> 同じように teratail を機械翻訳したサイトが増えてきた場合には別のリポジトリでプロジェクトを運用したいと思います

この件に関して、 teratail 等も含めたプログラミング関連の機械翻訳サイトをブロックすることを許容するリポジトリを検討しては頂けないでしょうか？

## evidence
- bleepcoder.com
  - https://github.com/facebookexperimental/Recoil/issues/546
  - https://bleepcoder.com/ja/recoil/690801759/can-an-atom-s-value-be-changed-from-a-non-react-environment

**Comment by 108EAA0A** [comment]
https://github.com/arosh/ublacklist-stackoverflow-translation/issues/51 の確認不足だったのでcloseします

**Comment by arosh** [comment]
@108EAA0A 
GitHub の README、Issue、Pull request などを機械翻訳したサイトについては以下のリポジトリで管理しています

https://github.com/arosh/ublacklist-github-translation
https://github.com/arosh/ublacklist-stackoverflow-translation/issues/51
