### ISSUE TITLE
Add uBlock Origin syntax file to support Firefox for Android

### ISSUE THREAD

**Issue by hirorpt** [arosh/ublacklist-stackoverflow-translation#76]
**Is your feature request related to a problem? Please describe.**
iOS Safari では拡張機能のサポートが次バージョンから追加されるのに対し、uBlacklist をインストールできるメジャーな Android ブラウザは存在しません。Firefox は例外的に拡張機能をサポートしていますが、任意の拡張機能をインストールできるのは Nightly やフォークに限られており、安定版には18の限られた拡張機能しか入れることができません。安定性やセキュリティを考慮すると Android で uBlacklist を快適に使用する方法はないといっていいでしょう。

**Describe the solution you'd like**
uBlock Origin をインストールした Firefox for Android で使用できるフィルタを生成する Github Action をこのリポジトリに追加します。uBlock Origin は Firefox for Android で真っ先にサポートされた拡張機能であり、よく広告ブロッカーとして認識されますが実際は汎用コンテンツブロッカーとして開発されています。専門拡張機能ならではの付加的な機能は使用できませんが、外部フィルタを購読して非表示にするという目的であれば十分実用的です。

**Describe alternatives you've considered**
Out of Scope だからフォークして自分のリポジトリでやるべきというのも正論ですが、検索エンジンから特定のサイトを消すフィルタというのは何よりも信用が重要ですので、できれば1つのリポジトリでやりたいと思います。

**Additional context**
設定例を[私のリポジトリ](https://github.com/hirorpt/ubo-stackoverflow-translation)で公開しています。実験的という立ち位置でメンテナンスの負担になれば削除という扱いで構いません。

**Comment by hirorpt** [comment]
Firefox 以外の Android ブラウザについて補足します。

<dl>
<dt>AdGuard アプリ + 任意のブラウザ</dt>
<dd>AdGuard という広告ブロックアプリは uBlock Origin と高い互換性があるため、私が変換したフィルタも使用できるはずです。ただしCA証明書のインストールが必要です。<dd>
<dt>拡張機能が使える Chromium ベースのブラウザ</dt>
<dd>Kiwi が有名ですが、テストしたところ uBlacklist はまともに動きません。uBlock Origin はインストールできますが、マネタイズの関係か Bing や Ecosia などの検索エンジンでは、有名なブロッカー拡張機能が動かなくなるようにハードコードされているため、こういった用途には不向きです。なお余談ですが、検索語が Kiwi のサーバに送信されるといった挙動もありuBlock Origin 開発チームは名指しで Kiwi を使用しないことを推奨しています。<br> 他の拡張機能が使えるブラウザについてはよく知りません。</dd>
</dl>

**Comment by arosh** [comment]
@hirorpt 
大変長らくお待たせいたしました。contrib/ublock にマージさせていただきました。リポジトリのオーナーとして積極的にメンテナンスする予定のものではないという点のみご了承ください。
