### ISSUE TITLE
www.webdevqa.jp.net

### ISSUE THREAD

**Issue by tats-u** [arosh/ublacklist-stackoverflow-translation#87]
it-swarm系の運営者が規制逃れのために新しいドメインを作成したようです。
例: `https://www.webdevqa.jp.net/ja/linux/%E3%83%AA%E3%83%A2%E3%83%BC%E3%83%88%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%AE%E5%AE%9F%E8%A1%8C/962630318/`

**Comment by arosh** [comment]
@tats-u 
ありがとうございます。#88 で対応しました。

**Comment by tats-u** [comment]
迅速なご対応ありがとうございます。
